version: '3.8'

services:
  php:
    extends:
      file: service1/auth-service.yml
      service: php
  nginx:
    extends:
      file: service1/auth-service.yml
      service: nginx
  mysql:
    extends:
      file: service1/auth-service.yml
      service: mysql

  php2:
    extends:
      file: service2/task-service.yml
      service: php2
  nginx2:
    extends:
      file: service2/task-service.yml
      service: nginx2
  mysql2:
    extends:
      file: service2/task-service.yml
      service: mysql2

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - .docker/kui/config.yml:/etc/kafkaui/dynamic_config.yaml

networks:
  localnetwork:
    name: worknetwork
